input1 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '3', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'}, 'Sections': {
                  'value': '{"id":1380,"item":"W44,W40,W36,W33,W30,W27,W24,W21,W18,W16,W14,W12,W10,W8X,W6,W5,W4","section_product_item":"39_91"}',
                  'unit': None}},
                   'Soil Properties': {'β active': {'value': '0', 'unit': '°'}, 'δ': {'value': '-1', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'},
                                       'Equivalent Fluid Pressure Passive': {'value': '1', 'unit': 'pcf'},
                                       'Φ': {'value': '-1', 'unit': '°'}, 'γ': {'value': '1', 'unit': 'pcf'},
                                       'Height of layer': {'value': '1', 'unit': 'ft'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"1","section_product_item":"41_94"}', 'unit': None},
                                       'γ ': {'value': '1', 'unit': 'pcf'}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Φ ': {'value': '1', 'unit': '°'},
                                       'Retaining Height': {'value': '1', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"Uniform","section_product_item":"40_92"}',
                                   'unit': None}, 'q  ': {'value': '1', 'unit': None},
                  'q   ': {'value': '1', 'unit': None}, 'q ': {'value': '1', 'unit': None},
                  'q': {'value': '1', 'unit': None}},
                   'Lagging': {'Ph max': {'value': '1', 'unit': 'psf'}, 'Fb': {'value': '1', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"1 x 2","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}
input3 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '6', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'}, 'Sections': {
                  'value': '{"id":1380,"item":"W44,W40,W36,W33,W30,W27,W24,W21,W18,W16,W14,W12,W10,W8X,W6,W5,W4","section_product_item":"39_91"}',
                  'unit': None}},
                   'Soil Properties': {'β active': {'value': '0', 'unit': '°'}, 'δ': {'value': '-1', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'},
                                       'Water started from top of this layer?': {'value': 'No', 'unit': None},
                                       'Equivalent Fluid Pressure Passive': {'value': '1', 'unit': 'pcf'},
                                       'Φ': {'value': '-1', 'unit': '°'}, 'γ': {'value': '1', 'unit': 'pcf'},
                                       'Water started from top of this layer? ': {'value': 'No', 'unit': None},
                                       'Height of layer': {'value': '1', 'unit': 'ft'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"1","section_product_item":"41_94"}', 'unit': None},
                                       'γ ': {'value': '1', 'unit': 'pcf'}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Φ ': {'value': '1', 'unit': '°'},
                                       'Retaining Height': {'value': '1', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"Uniform","section_product_item":"40_92"}',
                                   'unit': None}, 'q  ': {'value': '1', 'unit': None},
                  'q   ': {'value': '1', 'unit': None}, 'q ': {'value': '1', 'unit': None},
                  'q': {'value': '1', 'unit': None}},
                   'Lagging': {'Ph max': {'value': '1', 'unit': 'psf'}, 'Fb': {'value': '1', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"1 x 2","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input4 = {'information': {'title': '1', 'jobNo': '11', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '2', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '5', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '11', 'unit': 'in'},
                                    'Sections': {'value': '{"id":1380,"item":"W16,W14","section_product_item":"39_91"}',
                                                 'unit': None}},
                   'Soil Properties': {'Φ': {'value': '0.4', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                       'δ': {'value': '30', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"1","section_product_item":"41_94"}', 'unit': None}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Retaining Height': {'value': '11', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                   'unit': None}},
                   'Lagging': {'Ph max': {'value': '250', 'unit': 'psf'}, 'Fb': {'value': '25', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"1 x 2","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input5 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1.5', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '5', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'}, 'Sections': {
                  'value': '{"id":1380,"item":"W40,W33,W30","section_product_item":"39_91"}', 'unit': None}},
                   'Soil Properties': {'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                       'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"1","section_product_item":"41_94"}', 'unit': None}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Retaining Height': {'value': '11', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                   'unit': None}},
                   'Lagging': {'Ph max': {'value': '111', 'unit': 'psf'}, 'Fb': {'value': '11', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"1 x 2","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input6 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1.5', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '5', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '5', 'unit': 'in'},
                                    'Sections': {'value': '{"id":1380,"item":"W36","section_product_item":"39_91"}',
                                                 'unit': None}},
                   'Soil Properties': {'Φ': {'value': '11', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                       'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"1","section_product_item":"41_94"}', 'unit': None}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Retaining Height': {'value': '11', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"Point Load","section_product_item":"40_92"}',
                                'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                   'unit': None}, 'L1': {'value': '11', 'unit': 'ft'},
                  'q  ': {'value': '11', 'unit': None}, 'q ': {'value': '11', 'unit': None},
                  'q': {'value': '11', 'unit': None}, 'Ɵ': {'value': '0', 'unit': None}},
                   'Lagging': {'Ph max': {'value': '111', 'unit': 'psf'}, 'Fb': {'value': '11', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"1 x 2","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input7 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1.8', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '5', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'}, 'Sections': {
                  'value': '{"id":1380,"item":"W40,W36,W30","section_product_item":"39_91"}', 'unit': None}},
                   'Soil Properties': {'β active': {'value': '0', 'unit': '°'}, 'δ': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'}, 'Φ': {'value': '30', 'unit': '°'},
                                       'γ': {'value': '120', 'unit': 'pcf'},
                                       'Height of layer': {'value': '5', 'unit': 'ft'}, 'Soil Layer Number': {
                           'value': '{"id":1437,"item":"2","section_product_item":"41_94"}', 'unit': None},
                                       'γ ': {'value': '125', 'unit': 'pcf'}, 'Formula': {
                           'value': '{"id":1439,"item":"Rankine","section_product_item":"41_94"}', 'unit': None},
                                       'Φ ': {'value': '36', 'unit': '°'},
                                       'Retaining Height': {'value': '10', 'unit': 'ft'},
                                       'Water level at top of this layer? ': {'value': 'Yes', 'unit': None}},
                   'Surcharge': {'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}',
                                               'unit': None},
                                 'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}',
                                                'unit': None}, 'Load Type  ': {
                           'value': '{"id":1383,"item":"Point Load","section_product_item":"40_92"}', 'unit': None},
                                 'Load Type   ': {
                                     'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                     'unit': None}, 'q  ': {'value': '10000', 'unit': None},
                                 'Ɵ  ': {'value': '0', 'unit': None}, 'L1  ': {'value': '6', 'unit': 'ft'}},
                   'Lagging': {'Ph max': {'value': '411', 'unit': 'psf'}, 'Fb': {'value': '54', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"3 x 14","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input8 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': '1'}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1.5', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '6.5', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'}, 'Sections': {
                  'value': '{"id":1380,"item":"W40,W33,W30","section_product_item":"39_91"}', 'unit': None}},
                   'Soil Properties': {'β active': {'value': '0', 'unit': '°'}, 'δ': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'},
                                       'Ka Surcharge': {'value': '0.52', 'unit': None},
                                       'Equivalent Fluid Pressure Active': {'value': '32', 'unit': 'pcf'},
                                       'Equivalent Fluid Pressure Passive': {'value': '75', 'unit': 'pcf'},
                                       'Φ': {'value': '36', 'unit': '°'}, 'γ': {'value': '202', 'unit': 'pcf'},
                                       'Height of layer': {'value': '5', 'unit': 'ft'},
                                       'γ ': {'value': '120', 'unit': 'pcf'}, 'Formula': {
                           'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                       'Φ ': {'value': '23', 'unit': '°'},
                                       'Retaining Height': {'value': '10', 'unit': 'ft'},
                                       'Water level at top of this layer? ': {'value': 'Yes', 'unit': None},
                                       'Height of layer ': {'value': '10', 'unit': 'ft'},
                                       'γ  ': {'value': '234', 'unit': 'pcf'}, 'Φ  ': {'value': '45', 'unit': '°'},
                                       'δ  ': {'value': '0', 'unit': '°'}, 'β active  ': {'value': '0', 'unit': '°'},
                                       'β passive  ': {'value': '0', 'unit': '°'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"Uniform","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                   'unit': None}, 'q  ': {'value': '1235', 'unit': None}},
                   'Lagging': {'Ph max': {'value': '123', 'unit': 'psf'}, 'Fb': {'value': '43', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"2 x 12","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input9 = {'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                          'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
          'data': {'General data': {'FS': {'value': '1.5', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                                    'E': {'value': '29000', 'unit': 'ksi'},
                                    'Pile Spacing': {'value': '6', 'unit': 'ft'},
                                    'Allowable Deflection': {'value': '0.5', 'unit': 'in'},
                                    'Sections': {'value': '{"id":1380,"item":"","section_product_item":"39_91"}',
                                                 'unit': None}},
                   'Soil Properties': {'Ka Surcharge': {'value': '1.5', 'unit': None},
                                       'Equivalent Fluid Pressure Active': {'value': '35', 'unit': 'pcf'},
                                       'Equivalent Fluid Pressure Passive': {'value': '250', 'unit': 'pcf'},
                                       'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                       'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                       'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                           'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                       'Retaining Height': {'value': '10', 'unit': 'ft'}}, 'Surcharge': {
                  'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
                  'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                                   'unit': None}, 'Surcharge Effective Depth': {'value': '', 'unit': 'ft'}},
                   'Lagging': {'Ph max': {'value': '200', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                               'Timber Size': {'value': '{"id":1403,"item":"4 x 14","section_product_item":"42_93"}',
                                               'unit': None}}}, 'type': 1, 'number_of_projects': 1}
DR_project1_input3 = {
    'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                    'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '0.5', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W40,W33,W30","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1.5', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '35', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '250', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '15', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                             'unit': None}, 'Surcharge Effective Depth': {'value': '', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '200', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"4 x 14","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}
DR_project1_input2 = {
    'information': {'title': '1', 'jobNo': '1', 'designer': '1', 'checker': '1', 'company': '1', 'client': '1',
                    'unit': 'us', 'date': None, 'comment': None, 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '36', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '0.5', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W40,W33,W30","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1.5', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '25', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '500', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '26', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"40_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"40_92"}',
                             'unit': None}, 'Surcharge Effective Depth': {'value': '10', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '200', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"4 x 14","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}
input_GRAMERCY = {
    'information': {'title': '1848 GRAMERCY PL', 'jobNo': '1848 GRAMERCY PL',
                    'designer': 'AMIA ENGINEERING',
                    'checker': '-', 'company': 'AMIA ENGINEERING', 'client': '1848 GRAMERCY PL', 'unit': 'us',
                    'date': None, 'comment': "", 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '50', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '5', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W24","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '31', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '600', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '15', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"48_92"}',
                          'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"48_92"}',
                           'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"48_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"48_92"}',
                             'unit': None},
            'q': {'value': '100', 'unit': None}, 'L1 ': {'value': '6', 'unit': 'ft'},
            'q ': {'value': '100', 'unit': None}, 'q  ': {'value': '100', 'unit': None},
            'q   ': {'value': '100', 'unit': None},
            'Surcharge Effective Depth': {'value': '15', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '400', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"3 x 12","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}

comment = "#41 to #50"
input_Reseda = {
    'information': {'title': '6909-6923 N RESEDA', 'jobNo': '6909-6923 N RESEDA',
                    'designer': 'AMIA ENGINEERING',
                    'checker': '-', 'company': 'AMIA ENGINEERING', 'client': '6909-6923 N RESEDA', 'unit': 'us',
                    'date': None, 'comment': "", 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '50', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '0.9', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W24","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '34', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '250', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '13.5', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"48_92"}',
                          'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"48_92"}',
                           'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"48_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"48_92"}',
                             'unit': None},
            'q': {'value': '100', 'unit': None}, 'L1 ': {'value': '6', 'unit': 'ft'},
            'q ': {'value': '100', 'unit': None}, 'q  ': {'value': '100', 'unit': None},
            'q   ': {'value': '100', 'unit': None},
            'Surcharge Effective Depth': {'value': '15', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '400', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"3 x 12","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}
input2_ = {
    'information': {'title': '837-849 LE DOUX RD', 'jobNo': '837-849 LE DOUX RD',
                    'designer': 'AMIA ENGINEERING',
                    'checker': '-', 'company': 'AMIA ENGINEERING', 'client': '837-849 LE DOUX RD', 'unit': 'us',
                    'date': None, 'comment': comment, 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '50', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '10', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W21","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '46', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '250', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '13.5', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"48_92"}',
                          'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"48_92"}',
                           'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"48_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"48_92"}',
                             'unit': None},
            'q': {'value': '90', 'unit': None}, 'L1 ': {'value': '1', 'unit': 'ft'},
            'q ': {'value': '4000', 'unit': None}, 'q  ': {'value': '100', 'unit': None},
            'q   ': {'value': '100', 'unit': None},
            'Surcharge Effective Depth': {'value': '10', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '400', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"4 x 12","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}
comment = "#23 to #25"
input2_Sanmarino = {
    'information': {'title': '2811 SAN MARINO STREET', 'jobNo': '2811 SAN MARINO STREET',
                    'designer': 'AMIA ENGINEERING',
                    'checker': '-', 'company': 'AMIA ENGINEERING', 'client': '2811 SAN MARINO STREET', 'unit': 'us',
                    'date': None, 'comment': comment, 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '50', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '0.5', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W27","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '32', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '600', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '14', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"Uniform","section_product_item":"48_92"}',
                          'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"No Load","section_product_item":"48_92"}',
                           'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"48_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"48_92"}',
                             'unit': None},
            'q': {'value': '90', 'unit': None}, 'L1 ': {'value': '1', 'unit': 'ft'},
            'q ': {'value': '4000', 'unit': None}, 'q  ': {'value': '100', 'unit': None},
            'q   ': {'value': '100', 'unit': None},
            'Surcharge Effective Depth': {'value': '10', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '400', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"4 x 12","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}

input2 = {
    'information': {'title': 'Gramercy', 'jobNo': '837-849 LE DOUX RD',
                    'designer': 'AMIA ENGINEERING',
                    'checker': '-', 'company': 'AMIA ENGINEERING', 'client': '837-849 LE DOUX RD', 'unit': 'us',
                    'date': None, 'comment': comment, 'other': None}, 'product_id': 26, 'user_id': 44,
    'data': {'General data': {'FS': {'value': '1.3', 'unit': None}, 'Fy': {'value': '50', 'unit': 'ksi'},
                              'E': {'value': '29000', 'unit': 'ksi'},
                              'Pile Spacing': {'value': '8.0', 'unit': 'ft'},
                              'Allowable Deflection': {'value': '10', 'unit': 'in'},
                              'Sections': {
                                  'value': '{"id":1380,"item":"W21","section_product_item":"39_91"}',
                                  'unit': None}},
             'Soil Properties': {'Ka Surcharge': {'value': '1', 'unit': None},
                                 'Equivalent Fluid Pressure Active': {'value': '30', 'unit': 'pcf'},
                                 'Equivalent Fluid Pressure Passive': {'value': '320', 'unit': 'pcf'},
                                 'Φ': {'value': '0', 'unit': '°'}, 'γ': {'value': '20', 'unit': 'pcf'},
                                 'δ': {'value': '0', 'unit': '°'}, 'β active': {'value': '0', 'unit': '°'},
                                 'β passive': {'value': '0', 'unit': '°'}, 'Formula': {
                     'value': '{"id":1439,"item":"User Defined","section_product_item":"41_94"}', 'unit': None},
                                 'Retaining Height': {'value': '11.33', 'unit': 'ft'}}, 'Surcharge': {
            'Load Type': {'value': '{"id":1381,"item":"No Load","section_product_item":"48_92"}',
                          'unit': None},
            'Load Type ': {'value': '{"id":1382,"item":"Line Load","section_product_item":"48_92"}',
                           'unit': None},
            'Load Type  ': {'value': '{"id":1383,"item":"No Load","section_product_item":"48_92"}', 'unit': None},
            'Load Type   ': {'value': '{"id":1384,"item":"No Load","section_product_item":"48_92"}',
                             'unit': None},
            'q': {'value': '90', 'unit': None}, 'L1 ': {'value': '7.67', 'unit': 'ft'},
            'q ': {'value': '2000', 'unit': None}, 'q  ': {'value': '100', 'unit': None},
            'q   ': {'value': '100', 'unit': None},
            'Surcharge Effective Depth': {'value': '10', 'unit': 'ft'}},
             'Lagging': {'Ph max': {'value': '400', 'unit': 'psf'}, 'Fb': {'value': '0.9', 'unit': 'ksi'},
                         'Timber Size': {'value': '{"id":1403,"item":"4 x 12","section_product_item":"42_93"}',
                                         'unit': None}}}, 'type': 1, 'number_of_projects': 1}


